apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-notifier
  namespace: slack-integration-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-notifier
  template:
    metadata:
      labels:
        app: slack-notifier
    spec:
      serviceAccountName: slack-notifier-sa
      containers:
        - name: slack-notifier
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "env && sleep 3600"]
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: slack-notifier-config
                  key: APP_ENV
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: slack-notifier-config
                  key: LOG_LEVEL
            - name: RETRY_COUNT
              valueFrom:
                configMapKeyRef:
                  name: slack-notifier-config
                  key: RETRY_COUNT
            - name: SLACK_WEBHOOK_URL_PR
              valueFrom:
                secretKeyRef:
                  name: slack-webhook-secret
                  key: SLACK_WEBHOOK_URL_PR
            - name: SLACK_WEBHOOK_URL_CD
              valueFrom:
                secretKeyRef:
                  name: slack-webhook-secret
                  key: SLACK_WEBHOOK_URL_CD
