apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-secret
  namespace: slack-integration-dev
type: Opaque
stringData:
  SLACK_WEBHOOK_URL_PR: "https://hooks.slack.com/services/REPLACE/PRME"
  SLACK_WEBHOOK_URL_CD: "https://hooks.slack.com/services/REPLACE/CDME"
