apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: slack-integration-run-
  namespace: slack-integration-dev
spec:
  pipelineRef:
    name: slack-integration-pipeline

  params:
    - name: event-type
      value: pr
    - name: status
      value: succeeded
    - name: pipeline-name
      value: pr-validation

  workspaces:
    - name: shared-source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
