apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: go-test
  namespace: slack-integration-dev
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: golang:1.22
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -eu

        echo "Running Go tests..."
        go test ./...